import { NextRequest, NextResponse } from 'next/server';
import sgMail from '@sendgrid/mail';

// Set SendGrid API key
if (process.env.SENDGRID_API_KEY) {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);
}

export async function POST(request: NextRequest) {
  try {
    const { email, name, source, timestamp } = await request.json();

    if (!email || !name || !source) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const sourceTitle = source === 'ai-masterclass' ? 'VAI Masterclass' : 'VAI Toolkit';
    const fromEmail = process.env.SENDGRID_FROM_EMAIL || 'noreply@ventarosales.com';
    const adminEmail = 'chris.t@ventarosales.com';

    // Email to admin (Chris)
    const adminEmailContent = {
      to: adminEmail,
      from: fromEmail,
      subject: `🚀 New ${sourceTitle} Subscription Interest`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8fafc;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px;">
            <h1 style="color: white; margin: 0; font-size: 28px;">🎯 New Subscription Interest!</h1>
          </div>
          
          <div style="background: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
            <h2 style="color: #2d3748; margin-top: 0;">Subscription Details</h2>
            
            <div style="background: #f7fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <p style="margin: 10px 0; color: #4a5568;"><strong>📧 Email:</strong> ${email}</p>
              <p style="margin: 10px 0; color: #4a5568;"><strong>👤 Name:</strong> ${name}</p>
              <p style="margin: 10px 0; color: #4a5568;"><strong>📚 Product:</strong> ${sourceTitle}</p>
              <p style="margin: 10px 0; color: #4a5568;"><strong>⏰ Time:</strong> ${new Date(timestamp).toLocaleString()}</p>
            </div>
            
            <div style="background: #e6fffa; border-left: 4px solid #38b2ac; padding: 15px; margin: 20px 0;">
              <p style="margin: 0; color: #234e52;"><strong>💡 Action Required:</strong> This user is interested in subscribing to ${sourceTitle}. Follow up to convert them to a paid member!</p>
            </div>
            
            <div style="text-align: center; margin-top: 30px;">
              <a href="mailto:${email}" style="background: #667eea; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold;">📧 Contact User</a>
            </div>
          </div>
          
          <div style="text-align: center; margin-top: 20px; color: #718096; font-size: 14px;">
            <p>This email was automatically generated by the Ventaro AI subscription system.</p>
          </div>
        </div>
      `
    };

    // Email to user
    const userEmailContent = {
      to: email,
      from: fromEmail,
      subject: `🎉 Welcome! Your ${sourceTitle} Access is Coming Soon`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8fafc;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px;">
            <h1 style="color: white; margin: 0; font-size: 28px;">🎯 Welcome to ${sourceTitle}!</h1>
          </div>
          
          <div style="background: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
            <h2 style="color: #2d3748; margin-top: 0;">Hi ${name}! 👋</h2>
            
            <p style="color: #4a5568; line-height: 1.6;">Thank you for your interest in <strong>${sourceTitle}</strong>! We're excited to have you on board.</p>
            
            <div style="background: #e6fffa; border-left: 4px solid #38b2ac; padding: 20px; margin: 25px 0; border-radius: 0 8px 8px 0;">
              <h3 style="color: #234e52; margin-top: 0;">🚀 What's Next?</h3>
              <ul style="color: #234e52; margin: 0; padding-left: 20px;">
                <li>You'll be among the first to get access when we launch</li>
                <li>We'll send you exclusive updates and early-bird pricing</li>
                <li>Get ready for game-changing AI tools and training</li>
              </ul>
            </div>
            
            <div style="background: #fff5f5; border-left: 4px solid #f56565; padding: 20px; margin: 25px 0; border-radius: 0 8px 8px 0;">
              <h3 style="color: #742a2a; margin-top: 0;">⚡ Pro Tip</h3>
              <p style="color: #742a2a; margin: 0;">Keep an eye on your inbox! We'll be sending you exclusive content and first access to ${sourceTitle} very soon.</p>
            </div>
            
            <div style="text-align: center; margin-top: 30px;">
              <a href="https://ventarosales.com/membership" style="background: #667eea; color: white; padding: 15px 30px; text-decoration: none; border-radius: 8px; font-weight: bold; font-size: 16px;">🎯 Complete Your Membership</a>
            </div>
          </div>
          
          <div style="text-align: center; margin-top: 20px; color: #718096; font-size: 14px;">
            <p>Questions? Reply to this email or contact us at <a href="mailto:chris.t@ventarosales.com" style="color: #667eea;">chris.t@ventarosales.com</a></p>
            <p>🔒 Your email is secure • 📧 Unsubscribe anytime • ⚡ First access guaranteed</p>
          </div>
        </div>
      `
    };

    // Send emails
    if (process.env.SENDGRID_API_KEY) {
      await Promise.all([
        sgMail.send(adminEmailContent),
        sgMail.send(userEmailContent)
      ]);
    } else {
      console.log('SendGrid not configured, emails would be sent to:');
      console.log('Admin:', adminEmail);
      console.log('User:', email);
    }

    return NextResponse.json({ 
      success: true, 
      message: 'Subscription interest recorded and emails sent' 
    });

  } catch (error: any) {
    console.error('❌ SUBSCRIPTION INTEREST: Error (showing success to user):', error);
    
    // Always show success to user even if there are technical issues
    return NextResponse.json({
      success: true,
      message: 'Thank you for your interest! We\'ll be in touch soon with exclusive access details.'
    });
  }
}